spring.application.name=chargeup
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/major?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=#Sujal200427
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=Q2hhcmdlVXBTZWN1cmVEZW1vSldUU2VjcmV0S2V5Rm9yQ2hhcmdlVXAyMDI2
app.jwt.expiration-ms=86400000

razorpay.key.id=rzp_test_RwvdN24x3arIw6
razorpay.key.secret=17Yge36s66G4sul1cE4bpTEn
razorpay.currency=INR
razorpay.webhook.secret=U@FVsnQ59fRM6ZL

logging.level.org.springframework.security=INFO
